export const iconMap = {
  ".js": "⚡",
  ".jsx": "⚛️",
  ".ts": "🔷",
  ".tsx": "🔷",
  ".vue": "💚",
  ".svelte": "🧡",
  ".java": "☕",
  ".c": "🔧",
  ".cpp": "⚙️",
  ".cxx": "⚙️",
  ".cc": "⚙️",
  ".cs": "💎",
  ".env": "⚙️",
  ".example": "⚙️",
  ".go": "🐹",
  ".py": "🐍",
  ".pyw": "🐍",
  ".rb": "💎",
  ".php": "🐘",
  ".swift": "🦉",
  ".kt": "🎯",
  ".rs": "🦀",
  ".sh": "🐚",
  ".dart": "🎯",
  ".scala": "🌟",
  ".clj": "🔮",
  ".r": "📊",
  ".m": "📱",
  ".mm": "📱",
  ".pl": "🐪",
  ".perl": "🐪",
  ".lua": "🌙",
  ".elm": "🌳",
  ".ex": "💧",
  ".exs": "💧",
  ".erl": "📞",
  ".hrl": "📞",
  ".hs": "λ",

  ".env": "🔐",
  ".env.local": "🔐",
  ".env.example": "🔐",
  ".json": "📋",
  ".yaml": "📋",
  ".yml": "📋",
  ".toml": "📋",
  ".ini": "⚙️",
  ".config.js": "⚙️",
  ".conf": "⚙️",
  ".lock": "🔒",
  ".properties": "📋",
  ".cfg": "⚙️",
  ".settings": "⚙️",
  ".plist": "📋",
  ".xml": "📄",
  ".config": "⚙️",
  ".rc": "⚙️",
  ".editorconfig": "✏️",

  ".md": "📝",
  ".markdown": "📝",
  ".txt": "📄",
  ".rst": "📄",
  ".doc": "📄",
  ".docx": "📄",
  ".pdf": "📕",
  ".rtf": "📄",
  ".tex": "📄",
  ".log": "📋",
  ".readme": "📖",
  ".license": "📜",
  ".changelog": "📜",
  ".authors": "👥",
  ".contributors": "👥",

  ".gitignore": "🚫",
  ".gitattributes": "🏷️",
  ".gitmodules": "📦",
  ".gitkeep": "📌",
  ".gitmessage": "💬",
  ".gitconfig": "⚙️",

  ".png": "🖼️",
  ".jpg": "🖼️",
  ".jpeg": "🖼️",
  ".gif": "🎞️",
  ".svg": "🎨",
  ".ico": "🔷",
  ".webp": "🖼️",
  ".bmp": "🖼️",
  ".tiff": "🖼️",
  ".tif": "🖼️",
  ".psd": "🎨",
  ".ai": "🎨",
  ".sketch": "✏️",
  ".figma": "🎨",

  ".mp4": "🎬",
  ".avi": "🎬",
  ".mov": "🎬",
  ".wmv": "🎬",
  ".flv": "🎬",
  ".webm": "🎬",
  ".mkv": "🎬",
  ".m4v": "🎬",

  ".mp3": "🎵",
  ".wav": "🎵",
  ".flac": "🎵",
  ".aac": "🎵",
  ".ogg": "🎵",
  ".wma": "🎵",
  ".m4a": "🎵",

  ".css": "🎨",
  ".scss": "🎨",
  ".sass": "🎨",
  ".less": "🎨",
  ".stylus": "🎨",
  ".woff": "🔤",
  ".woff2": "🔤",
  ".ttf": "🔤",
  ".otf": "🔤",
  ".eot": "🔤",

  ".html": "🌐",
  ".htm": "🌐",
  ".xhtml": "🌐",
  ".shtml": "🌐",
  ".ejs": "🌐",
  ".hbs": "🌐",
  ".handlebars": "🌐",
  ".mustache": "🌐",
  ".pug": "🌐",
  ".jade": "🌐",
  ".haml": "🌐",

  ".csv": "📊",
  ".tsv": "📊",
  ".xls": "📊",
  ".xlsx": "📊",
  ".json": "📊",
  ".xml": "📊",
  ".sql": "🗃️",
  ".parquet": "📊",

  ".db": "🗄️",
  ".sqlite": "🗄️",
  ".sqlite3": "🗄️",
  ".mdb": "🗄️",
  ".accdb": "🗄️",
  ".dbf": "🗄️",

  ".bat": "⚡",
  ".ps1": "💻",
  ".cmd": "⚡",
  ".com": "⚡",
  ".bash": "🐚",
  ".zsh": "🐚",
  ".fish": "🐠",
  ".csh": "🐚",
  ".ksh": "🐚",
  ".tcsh": "🐚",
  ".awk": "🔧",
  ".sed": "🔧",

  ".test.js": "🧪",
  ".spec.js": "🧪",
  ".test.ts": "🧪",
  ".spec.ts": "🧪",
  ".test.jsx": "🧪",
  ".spec.jsx": "🧪",
  ".test.tsx": "🧪",
  ".spec.tsx": "🧪",
  ".test.py": "🧪",
  ".spec.py": "🧪",

  ".zip": "📦",
  ".rar": "📦",
  ".7z": "📦",
  ".tar": "📦",
  ".gz": "📦",
  ".bz2": "📦",
  ".xz": "📦",
};

export const extMap = {
  ".js": "sourceFile",
  ".jsx": "sourceFile",
  ".ts": "sourceFile",
  ".tsx": "sourceFile",
  ".vue": "sourceFile",
  ".svelte": "sourceFile",
  ".java": "sourceFile",
  ".c": "sourceFile",
  ".cpp": "sourceFile",
  ".cxx": "sourceFile",
  ".cc": "sourceFile",
  ".cs": "sourceFile",
  ".go": "sourceFile",
  ".py": "sourceFile",
  ".pyw": "sourceFile",
  ".rb": "sourceFile",
  ".php": "sourceFile",
  ".swift": "sourceFile",
  ".kt": "sourceFile",
  ".rs": "sourceFile",
  ".sh": "sourceFile",
  ".dart": "sourceFile",
  ".scala": "sourceFile",
  ".clj": "sourceFile",
  ".r": "sourceFile",
  ".m": "sourceFile",
  ".mm": "sourceFile",
  ".pl": "sourceFile",
  ".perl": "sourceFile",
  ".lua": "sourceFile",
  ".elm": "sourceFile",
  ".ex": "sourceFile",
  ".exs": "sourceFile",
  ".erl": "sourceFile",
  ".hrl": "sourceFile",
  ".hs": "sourceFile",

  ".env": "configFile",
  ".env.local": "configFile",
  ".env.example": "configFile",
  ".example": "configFile",
  ".json": "configFile",
  ".yaml": "configFile",
  ".yml": "configFile",
  ".toml": "configFile",
  ".ini": "configFile",
  ".config.js": "configFile",
  ".conf": "configFile",
  ".lock": "configFile",
  ".env.production": "configFile",
  ".env.development": "configFile",
  ".properties": "configFile",
  ".cfg": "configFile",
  ".settings": "configFile",
  ".plist": "configFile",
  ".xml": "configFile",
  ".config": "configFile",
  ".rc": "configFile",
  ".editorconfig": "configFile",

  ".md": "docFile",
  ".markdown": "docFile",
  ".txt": "docFile",
  ".rst": "docFile",
  ".doc": "docFile",
  ".docx": "docFile",
  ".pdf": "docFile",
  ".rtf": "docFile",
  ".tex": "docFile",
  ".log": "docFile",
  ".readme": "docFile",
  ".license": "docFile",
  ".changelog": "docFile",
  ".authors": "docFile",
  ".contributors": "docFile",

  ".gitignore": "gitFile",
  ".gitattributes": "gitFile",
  ".gitmodules": "gitFile",
  ".gitkeep": "gitFile",
  ".gitmessage": "gitFile",
  ".gitconfig": "gitFile",

  ".png": "imageFile",
  ".jpg": "imageFile",
  ".jpeg": "imageFile",
  ".gif": "imageFile",
  ".svg": "imageFile",
  ".ico": "imageFile",
  ".webp": "imageFile",
  ".bmp": "imageFile",
  ".tiff": "imageFile",
  ".tif": "imageFile",
  ".psd": "imageFile",
  ".ai": "imageFile",
  ".sketch": "imageFile",
  ".figma": "imageFile",

  ".mp4": "videoFile",
  ".avi": "videoFile",
  ".mov": "videoFile",
  ".wmv": "videoFile",
  ".flv": "videoFile",
  ".webm": "videoFile",
  ".mkv": "videoFile",
  ".m4v": "videoFile",

  ".mp3": "audioFile",
  ".wav": "audioFile",
  ".flac": "audioFile",
  ".aac": "audioFile",
  ".ogg": "audioFile",
  ".wma": "audioFile",
  ".m4a": "audioFile",

  ".css": "assetFile",
  ".scss": "assetFile",
  ".sass": "assetFile",
  ".less": "assetFile",
  ".stylus": "assetFile",
  ".woff": "assetFile",
  ".woff2": "assetFile",
  ".ttf": "assetFile",
  ".otf": "assetFile",
  ".eot": "assetFile",

  ".html": "htmlFile",
  ".htm": "htmlFile",
  ".xhtml": "htmlFile",
  ".shtml": "htmlFile",
  ".ejs": "htmlFile",
  ".hbs": "htmlFile",
  ".handlebars": "htmlFile",
  ".mustache": "htmlFile",
  ".pug": "htmlFile",
  ".jade": "htmlFile",
  ".haml": "htmlFile",

  ".csv": "dataFile",
  ".tsv": "dataFile",
  ".xls": "dataFile",
  ".xlsx": "dataFile",
  ".json": "dataFile",
  ".xml": "dataFile",
  ".sql": "dataFile",
  ".parquet": "dataFile",

  ".db": "databaseFile",
  ".sqlite": "databaseFile",
  ".sqlite3": "databaseFile",
  ".mdb": "databaseFile",
  ".accdb": "databaseFile",
  ".dbf": "databaseFile",

  ".bat": "scriptFile",
  ".ps1": "scriptFile",
  ".cmd": "scriptFile",
  ".com": "scriptFile",
  ".bash": "scriptFile",
  ".zsh": "scriptFile",
  ".fish": "scriptFile",
  ".csh": "scriptFile",
  ".ksh": "scriptFile",
  ".tcsh": "scriptFile",
  ".awk": "scriptFile",
  ".sed": "scriptFile",

  ".test.js": "testFile",
  ".spec.js": "testFile",
  ".test.ts": "testFile",
  ".spec.ts": "testFile",
  ".test.jsx": "testFile",
  ".spec.jsx": "testFile",
  ".test.tsx": "testFile",
  ".spec.tsx": "testFile",
  ".test.py": "testFile",
  ".spec.py": "testFile",

  ".zip": "archiveFile",
  ".rar": "archiveFile",
  ".7z": "archiveFile",
  ".tar": "archiveFile",
  ".gz": "archiveFile",
  ".bz2": "archiveFile",
  ".xz": "archiveFile",

  Makefile: "buildFile",
  makefile: "buildFile",
  ".make": "buildFile",
  Dockerfile: "buildFile",
  dockerfile: "buildFile",
  ".dockerfile": "buildFile",
  "CMakeLists.txt": "buildFile",
  ".cmake": "buildFile",
  BUILD: "buildFile",
  "build.gradle": "buildFile",
  "pom.xml": "buildFile",
  "package.json": "buildFile",
};

export const classCode = [
  // Circles
  "classDef rootNode fill:#f72585,stroke:#f72585,stroke-width:4px,color:#ffffff,rx:50,ry:50,stroke-dasharray: 0",
  "classDef folderNode fill:#0abde3,stroke:#0abde3,stroke-width:4px,color:#ffffff,rx:50,ry:50,stroke-dasharray: 0",

  // Rectangles
  "classDef sourceFile fill:#27ae60,stroke:#229954,stroke-width:3px,color:#ffffff,rx:4,ry:4,stroke-dasharray: 0",
  "classDef configFile fill:#f39c12,stroke:#e67e22,stroke-width:3px,color:#2c3e50,rx:4,ry:4,stroke-dasharray: 0",
  "classDef docFile fill:#0077b6,stroke:#2980b9,stroke-width:3px,color:#ffffff,rx:4,ry:4,stroke-dasharray: 0",
  "classDef gitFile fill:#6a1b9a,stroke:#6a1b9a,stroke-width:3px,color:#ffffff,rx:4,ry:4,stroke-dasharray: 0",
  "classDef assetFile fill:#9b59b6,stroke:#8e44ad,stroke-width:3px,color:#ffffff,rx:4,ry:4,stroke-dasharray: 0",
  "classDef htmlFile fill:#f39c0f,stroke:#d35400,stroke-width:3px,color:#ffffff,rx:4,ry:4,stroke-dasharray: 0",
  "classDef dataFile fill:#1abc9c,stroke:#16a085,stroke-width:3px,color:#ffffff,rx:4,ry:4,stroke-dasharray: 0",
  "classDef scriptFile fill:#f1c40f,stroke:#f39c12,stroke-width:3px,color:#2c3e50,rx:4,ry:4,stroke-dasharray: 0",
  "classDef unknownFile fill:#95a5a6,stroke:#7f8c8d,stroke-width:3px,color:#2c3e50,rx:4,ry:4,stroke-dasharray: 0",
  "classDef testFile fill:#ff6b6b,stroke:#ee5a24,stroke-width:3px,color:#ffffff,rx:4,ry:4,stroke-dasharray: 0",
  "classDef buildFile fill:#5f27cd,stroke:#341f97,stroke-width:3px,color:#ffffff,rx:4,ry:4,stroke-dasharray: 0",
  "classDef databaseFile fill:#00d2d3,stroke:#01a3a4,stroke-width:3px,color:#ffffff,rx:4,ry:4,stroke-dasharray: 0",
  "classDef imageFile fill:#fd79a8,stroke:#fd79af,stroke-width:3px,color:#ffffff,rx:4,ry:4,stroke-dasharray: 0",
  "classDef videoFile fill:#ff3838,stroke:#ff2d92,stroke-width:3px,color:#ffffff,rx:4,ry:4,stroke-dasharray: 0",
  "classDef audioFile fill:#ff9f43,stroke:#ff6348,stroke-width:3px,color:#ffffff,rx:4,ry:4,stroke-dasharray: 0",
  "classDef archiveFile fill:#7bed9f,stroke:#5f27cd,stroke-width:3px,color:#ffffff,rx:4,ry:4,stroke-dasharray: 0",
];